// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh7EI7_fdl6nmJM_lU9IF6wKbqcGA7N2g',
    appId: '1:135827624937:web:088e4c6c71d6762fb57178',
    messagingSenderId: '135827624937',
    projectId: 'yfoz-2023',
    authDomain: 'yfoz-2023.firebaseapp.com',
    storageBucket: 'yfoz-2023.appspot.com',
    measurementId: 'G-X2MRP6H4KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR90MmmBWIho7cfCKoP5_M30r49y8zH3Q',
    appId: '1:135827624937:android:cce362680a376d04b57178',
    messagingSenderId: '135827624937',
    projectId: 'yfoz-2023',
    storageBucket: 'yfoz-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8zPcF3JxXgspORJLP28X07H3YveOJKU',
    appId: '1:135827624937:ios:7cf59594eadaed54b57178',
    messagingSenderId: '135827624937',
    projectId: 'yfoz-2023',
    storageBucket: 'yfoz-2023.appspot.com',
    androidClientId: '135827624937-lkb5pa1ncth5eaith4jv4beju5v8vbdc.apps.googleusercontent.com',
    iosClientId: '135827624937-vtqtu1bqmtvb4hslr6ojcnork0hajjji.apps.googleusercontent.com',
    iosBundleId: 'net.yfoz.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf8zPcF3JxXgspORJLP28X07H3YveOJKU',
    appId: '1:135827624937:ios:7cf59594eadaed54b57178',
    messagingSenderId: '135827624937',
    projectId: 'yfoz-2023',
    storageBucket: 'yfoz-2023.appspot.com',
    androidClientId: '135827624937-lkb5pa1ncth5eaith4jv4beju5v8vbdc.apps.googleusercontent.com',
    iosClientId: '135827624937-vtqtu1bqmtvb4hslr6ojcnork0hajjji.apps.googleusercontent.com',
    iosBundleId: 'net.yfoz.customer',
  );
}
