// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCEj2YbqrAlF0NDMYkdS8e5_UcKvjruIZM',
      appId: '1:575890868187:android:44d638da5fe6958b85c9fe',
      messagingSenderId: '575890868187',
      projectId: 'soldout-de9d4',
      storageBucket: 'soldout-de9d4.appspot.com',
      androidClientId: '575890868187-5v0ih68h4rojscild8phmcf2n3juejfk.apps.googleusercontent.com',
      deepLinkURLScheme: 'https://soldoutapp.page.link/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyC3LrR7ssgKQd2i1pbfpWNKlFiwOsJ7uuQ',
      appId: '1:441146186016:ios:1de3815d2bcebcd2cb5f45',
      messagingSenderId: '441146186016',
      projectId: 'soldout-99b4c',
      storageBucket: 'soldout-99b4c.appspot.com',
      iosClientId: '441146186016-qnm32s25oeffmadmqrhkg92oo21aflv1.apps.googleusercontent.com',
      iosBundleId: 'com.soldout.sa',
      deepLinkURLScheme: 'https://soldou.page.link/'
  );

}
